### ISSUE TITLE
replace light circles around towers with pixel art version sprites

### ISSUE THREAD

**Issue by plexsoup** [smclaughlan/GWJ52#102]
We want the edges of the light-circles to be pixelated, so the artists are providing pixel art for the zones of light around the towers.

swap out the draw() function for a sprite that scales when the towers upgrade "bigger"

**Comment by IMAFIREHAZARD** [comment]
@plexsoup is any further action planned on this? can we close?

**Comment by IMAFIREHAZARD** [comment]
Closing as implemented
