### ISSUE TITLE
FEATURE: Make creeps explode when tower is placed on top of them

### ISSUE THREAD

**Issue by plexsoup** [smclaughlan/GWJ52#115]
I think creeps might be blocking placement of towers (not 100% sure on this). If that's the case, it won't feel good for the player to keep hearing NO, you can't build there.

So creeps should not block tower placement. 
Make them instagib or knock back if player puts a tower on top of them.

**Comment by IMAFIREHAZARD** [comment]
Creeps do not block tower placement. Towers do not kill creeps @plexsoup can we close? Is there more work planned here?

**Comment by IMAFIREHAZARD** [comment]
Is more work planned here?

**Comment by IMAFIREHAZARD** [comment]
No further work approved before release
