### ISSUE TITLE
resize main window for better pixel art resolution

### ISSUE THREAD

**Issue by plexsoup** [smclaughlan/GWJ52#126]
6:04 PM]Suricato Guerrilheiro: also the window size is not 16:9 rn , it should be 1024x576, unless you dont care about it which is fine

**Comment by IMAFIREHAZARD** [comment]
@plexsoup @Ravensherald is there more work planned here? can we close?

**Comment by plexsoup** [comment]
NP. I changed the window resolution to 1024x576 as requested.
