### ISSUE TITLE
Creeps are spawning outside of the map

### ISSUE THREAD

**Issue by IMAFIREHAZARD** [smclaughlan/GWJ52#175]
![image](https://user-images.githubusercontent.com/101430646/208187837-bf721da4-52a7-48ce-9c24-dbb036c23ba9.png)
Creeps will sometimes spawn outside the map. This can cause lag.

**Comment by plexsoup** [comment]
I'm having trouble reproducing this problem.
The spawners are currently set to send the creeps toward the village, so they _shouldn't_ be spawning outside the map. 

I added keyboard shortcuts 9,0 to change the camera zoom. Wasn't able to see creeps outside the map.

**Comment by IMAFIREHAZARD** [comment]
Closing as CNR
