### ISSUE TITLE
Enemies overlapping too much - low priority

### ISSUE THREAD

**Issue by smclaughlan** [smclaughlan/GWJ52#183]
Low priority to fix, but would be nice to have

**Comment by IMAFIREHAZARD** [comment]
![image](https://user-images.githubusercontent.com/101430646/208193008-ac2d32c8-0385-47b2-b95e-0fe7e352f3c5.png)

**Comment by IMAFIREHAZARD** [comment]
is there more work planned here. can we close? @smclaughlan
