### ISSUE TITLE
Implement audio SFX assets

### ISSUE THREAD

**Issue by IMAFIREHAZARD** [smclaughlan/GWJ52#193]
The following audio SFX assets are in the Audio folder on dev but not yet implemented

- Creep attack
- Currency pick up
- Tower build

**Comment by IMAFIREHAZARD** [comment]
Loot pickup and tower build sounds added.

Creep attack still needed.

**Comment by plexsoup** [comment]
Creep getting injured noise is still placeholder "Ow" voice sounds.

**Comment by plexsoup** [comment]
I pushed the creep melee attack noise.

Someone else should test, to make sure all is as expected.

**Comment by IMAFIREHAZARD** [comment]
Closing as complete. Creep attack sounds are bad. Logging new ticket to track.
