### ISSUE TITLE
Create Win condition and Win Screen

### ISSUE THREAD

**Issue by plexsoup** [smclaughlan/GWJ52#197]
If we decide this is a persistent grind until you die game, like Dwarf Fortress, then we don't need a win screen. If we want a win screen, we need to implement the trigger and screen.

**Comment by IMAFIREHAZARD** [comment]
Win screen added, accessible through cheats

**Comment by IMAFIREHAZARD** [comment]
Also needs documentation in opening

**Comment by IMAFIREHAZARD** [comment]
Closing as implemented
