### ISSUE TITLE
Creeps are over tuned

### ISSUE THREAD

**Issue by IMAFIREHAZARD** [smclaughlan/GWJ52#204]

**Comment by IMAFIREHAZARD** [comment]
early in game, creeps are too powerful. shells, towers, and players die too easily

**Comment by IMAFIREHAZARD** [comment]
- Buff tower HP
- Buff golem HP
- Slow down creeps
- Spawn fewer creeps in early waves
- Add I-frames to all friendly objects (.5-1sec) after taking dmg

**Comment by plexsoup** [comment]
I buffed the Towers HP and added iFrames.
I gave the spare golems I-frames, but I didn't change their health.

Leaving creeps alone for now because I like fast moving enemies.

**Comment by IMAFIREHAZARD** [comment]
Closing as resolved.
