### ISSUE TITLE
BUG: Creep attack sounds are annoying

### ISSUE THREAD

**Issue by IMAFIREHAZARD** [smclaughlan/GWJ52#206]
Taking any recommendations. Likely easy fix is to revert to previous audio.

**Comment by IMAFIREHAZARD** [comment]
Any thoughts? Do we have more work planned here or ideas for a fix? Or can we close?

**Comment by rcsira** [comment]
How about adding a random pitch every time the sound is played so it doesn't sound monotonous?

**Comment by IMAFIREHAZARD** [comment]
Calling this fixed! Thanks @rcsira!
