### ISSUE TITLE
Lost ability to go full screen on title bar

### ISSUE THREAD

**Issue by IMAFIREHAZARD** [smclaughlan/GWJ52#216]
![title bar fullscreen](https://user-images.githubusercontent.com/101430646/208226905-2f7afe90-70f4-4975-8583-01a5e6ff38b6.png)

**Comment by plexsoup** [comment]
Not sure how this keeps getting changed.

The setting is in Godot: Project Settings: Display: Window: Resizable.

Keep it resizable.

I've set it back to resizable.
