### ISSUE TITLE
Highest upgraded yellow towers are missing enemies

### ISSUE THREAD

**Issue by smclaughlan** [smclaughlan/GWJ52#222]

**Comment by IMAFIREHAZARD** [comment]
Assigned to self for investigation.

**Comment by IMAFIREHAZARD** [comment]
Max level Yellow Towers always fire in the same direction and do not track enemies.

**Repro Steps**
1. Launch the game
2. Press play
3. Play intro animatic
4. Open debug menu
5. Add 300 ichor
6. Build 3 Yellow Towers
7. Upgrade each tower to max
8. Wait for enemies to spawn

**Expected Result**
Towers fire at creeps in range

**Actual Result**
Towers fire at 8 o' clock when creeps get in range

**Comment by plexsoup** [comment]
That was an oversight from the previous version of the tower, before it shot continuous lasers. I've updated the second projectile scene. Should be fixed now.
