### ISSUE TITLE
INVESTIGATION: Why is bespoke audio not playing?

### ISSUE THREAD

**Issue by IMAFIREHAZARD** [smclaughlan/GWJ52#236]
Missing sounds:

- Melee hit
- Tower shoot sound
- Strife are attacked sound
- Click sounds

Where are the files?
What files are currently hooked up?
What files should be hooked up?

**Comment by IMAFIREHAZARD** [comment]
Was unable to find nodes and figure out problems. will need assistance

**Comment by smclaughlan** [comment]
Added sounds as appropriate.
