### ISSUE TITLE
BUG: One golem is hidden behind the central tower

### ISSUE THREAD

**Issue by IMAFIREHAZARD** [smclaughlan/GWJ52#244]
![image](https://user-images.githubusercontent.com/101430646/208271132-05bcb3cb-a758-4ed1-858e-5b1454c4acf6.png)
Can we move the armor to the left so that the player can see it?

**Comment by rcsira** [comment]
I just looked at the `Village` scene. There's nothing there.

**Comment by IMAFIREHAZARD** [comment]
It may not be the right scene to check. Here's media of me doing it on the latest build.
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/101430646/208271950-cb79e888-0993-474b-8bcb-cdc425dc2c39.gif)

**Comment by IMAFIREHAZARD** [comment]
Also, after posting I noticed there's a bug where it won't remove the golem you occupy. I'm fine to let that slide though.

**Comment by IMAFIREHAZARD** [comment]
No golem behind the tower. Area for top right golem just larger than expected. Potential bug above related and does not exist.
