### ISSUE TITLE
BUG: Two crashing failures detected

### ISSUE THREAD

**Issue by IMAFIREHAZARD** [smclaughlan/GWJ52#250]
Two crashes were logged by @smclaughlan. This stub ticket was created to track them

**Comment by smclaughlan** [comment]
These should both be fixed, but these were:
* crashes on pressing the quit button on game end.
* crashes when the game ended while a tower was shooting.

**Comment by IMAFIREHAZARD** [comment]
Just experienced a crash in latest build. Possibly related to second issue.

**Comment by IMAFIREHAZARD** [comment]
Closing as fixed
