### ISSUE TITLE
FEATURE: Modify GLUEProjectile1.tscn and GLUEProjectile2.tscn for projectile shape

### ISSUE THREAD

**Issue by IMAFIREHAZARD** [smclaughlan/GWJ52#267]
(they're still called GLUE, despite being projectiles) - @plexsoup 
As a user, I want projectiles from blue towers to be shorter, fatter, and have be more rounded.

**Comment by plexsoup** [comment]
Closing this issue. New issue will be "rename GlueTurret and GLUEProjectile", because they're rapid-fire knock back, not glue.
