### ISSUE TITLE
FEATURE: Increase axe damage

### ISSUE THREAD

**Issue by IMAFIREHAZARD** [smclaughlan/GWJ52#273]
As a designer, I want the axe to deal 10 damage on hit.

**Comment by IMAFIREHAZARD** [comment]
changes in CameraAndDifficultyTuning

**Comment by smclaughlan** [comment]
Melee damage increased to 10, but may need further buffs since melee attacks put the player at high risk from enemies.

**Comment by IMAFIREHAZARD** [comment]
implemented. other changes recommended but not approved for work
