### ISSUE TITLE
"Easy Mode" button should be toggle instead of press.

### ISSUE THREAD

**Issue by plexsoup** [smclaughlan/GWJ52#304]
After pressing the Easy mode button, I want to be able to hide the easy mode again.

(Ultimately, the easy mode will go away, since it's primarily for debugging and play testing, but for now, make it a toggle.)

**Comment by rcsira** [comment]
How about making the Easy button appear only on debug builds? Is this possible?

**Comment by plexsoup** [comment]
https://docs.godotengine.org/en/stable/classes/class_os.html#class-os-method-is-debug-build

**Comment by rcsira** [comment]
Alright. Will work on it tomorrow.

**Comment by rcsira** [comment]
## Tasks
- [ ] Change button to toggle
- [ ] Make the button appear only on debug builds.
