### ISSUE TITLE
FEATURE: Create 2 new types of creeps, "big" and "fast"

### ISSUE THREAD

**Issue by plexsoup** [smclaughlan/GWJ52#51]
The art team is coming up with a variety of creep sprites. We'll need mechanics or variables for 

- Normal creep
- Big creep
- Armored creep
- Flying creep
- Burrowing creep

**Comment by IMAFIREHAZARD** [comment]
Is more work planned here? Is it implemented? Can we close?

**Comment by plexsoup** [comment]
I think more work is planned here. 
I set up two creep scenes for Suricate to add artwork after I'm away.
Creep2Bigger.tscn and Creep3Faster.tscn.

Seems like ThereIsNoJustice is working on ranged missile creeps too.
Let's Keep the ticket open for now.

**Comment by IMAFIREHAZARD** [comment]
Closing as WNF
