### ISSUE TITLE
Create tower upgrade mechanics

### ISSUE THREAD

**Issue by plexsoup** [smclaughlan/GWJ52#52]
Players expect to be able to upgrade their towers.

We need to figure out exactly how they do that.

Do we need upgrade buttons on each tower? Maybe the construction wrench will upgrade a tower if you "shoot" a tower while holding the wrench.

How do players choose what type of upgrade? How long should an upgrade take? How much does it cost? What types of upgrades are there?

Most tower defence games don't have a player running around, so it's easy to upgrade things through menus.

**Comment by IMAFIREHAZARD** [comment]
Closing as implemented
