### ISSUE TITLE
Various - notes from mtg Dec 11

### ISSUE THREAD

**Issue by plexsoup** [smclaughlan/GWJ52#59]
Bugs:
- Laser knock back is broken after introduction of melee knockback
- Initial towers don't have active collision shapes. (make them bases+turrets, not just turrets)

Design:
- What's the win condition? Maybe player buys their "win" with currency (light) at the base
- Move the shopping interface to the base so the player has to divide their time between hunting and defending
- Tower placement needs maximum range so player can't spread too quickly
- Tower placement needs more obvious feedback about requirements - insufficient cash, distance, etc.
- Player needs some starting cash, so they can place a couple of towers.
- Need a softer landing / onboarding / tutorial. (Maybe scene 1 is a small tutorial zone where they place the first 4 towers that show up when they start the real game)
- If the player is off hunting, they should get an edge-of-screen alert when the base is under attack.
- maybe give an edge of screen wave alert if the player is at the base and an offscreen spawner fires up a new wave.
- Make the village an exclusion zone, so no towers can be placed there (this might be auto-solved based on tower minimum distance requirements)
- Player should be able to destroy towers for a refund.
    - right click on tower while holding the construction wrench? Or interaction key (e or f)
- Towers, when placed, will snap to a grid, so they don't look untidy.

Backlog
- Plexsoup is still working on the tower wiring network. 
    - If the path to the source breaks, all downstream towers should lose power. 
    - When towers are depowered they should light up again when a new (powered) tower is placed nearby
    - player can't build in the dark, towers have a light aura / radius. new towers only go in the light. if part of the grid is dep-powered, there's no building there.

**Comment by IMAFIREHAZARD** [comment]
Closing as obsolete
