### ISSUE TITLE
review GitHub CI tools to see if it helps export to itch.io, especially for Mac

### ISSUE THREAD

**Issue by plexsoup** [smclaughlan/GWJ52#82]
In this thread: https://discord.com/channels/486990419230457876/1048710078347354122/1051552340672532611
They talk about CI tools in GitHub to make it easier to export for Mac.

Here's a yaml file someone used:
https://github.com/Lounge-Dev-Knights/gameoff-2022/blob/main/.github/workflows/release.yaml

Here's another workflow description:
https://github.com/firebelley/godot-export

**Comment by IMAFIREHAZARD** [comment]
@plexsoup can we close? is more work planned here?

**Comment by plexsoup** [comment]
I think we won't have time for this. It was more of a reference anyways.
