### ISSUE TITLE
Create crystal golems for the player to inhabit and control

### ISSUE THREAD

**Issue by plexsoup** [smclaughlan/GWJ52#85]
The player's avatar is a Dwarf Queen ghost, made of light.
The dwarf queen spirit can inhabit crystal golems / automatons.
These bodies serve as the game "lives". If the player runs out of golems, it's game over.
There should be a variety of golems scattered around the map for the player to discover and inhabit.

The player needs a spirit form and one or more golem forms.

**Comment by IMAFIREHAZARD** [comment]
Closing as implemented. Golems around the map mechanic now obsolete.
